name: db_proj

services:

    database:
        image: postgres:16
        restart: always
        ports:
            - "8051:5432" 
        environment:
            POSTGRES_PASSWORD: postgres
        volumes:
            - ./back/dumps/main.sql:/docker-entrypoint-initdb.d/main.sql
            - ./db_data:/var/lib/postgresql/data
            
volumes:
    data:
        driver: local